window.NOTEBOOK_BASE = "/";
window.NOTEBOOK_LIBRARY=[
 /*{url:"blog/2026-08-16-apparently-im-building-a-llama-company-now.html",
  title:"Apparently I'm building a llama company now",
  date:"2026-08-16",
  year:2026,
  tags: ["Making Things","Llama Scout","AuDHD","Behind the Site","Fox & Timber"],
  excerpt:"AutismOverland was supposed to get an update. A couple of days later it had become Llama Scout, with a new identity, and an increasingly ridiculous number of things competing for my attention.",
  hero:"img/blog/2026-08-16-001.jpeg",
  alt:"Llama Scout branding and website development in progress",
  readingTime:"Medium",
  searchText:"llama scout autism overland audhd executive dysfunction fox and timber website frontend backend membership paywall pricing coupons merchandise stuffed weighted llama bandanna shirts hats storefront advertising social media doordash medication side effects making things"
},*/
 {url:"blog/2026-08-09-ai-helped-me-find-my-job.html",
  title:"AI helped me find my job",
  date:"2026-08-09",
  year:2026,
  tags:["Making Things","Artificial Intelligence","Fox & Timber","Work","Technology"],
  excerpt:"I did not find AI because I wanted to replace work. I found it because I wanted to build things I could not build alone.",
  hero:"img/blog/2026-08-09-001.jpeg",
  alt:"A massive modern data center in the middle of a suburban neighborhood",
  readingTime:"Long",
  searchText:"artificial intelligence ai jobs employment fox and timber coffee company branding website coding data centers electricity water environment dependency accessibility creativity technology work"
 },
 {url:"blog/2026-08-02-the-things-photographs-leave-out.html",
  title:"The things photographs leave out",
  date:"2026-08-02",
  year:2026,
  tags:["Life Outside","Photography","Horizon","Reality","Field Notes"],
  excerpt:"The photographs are real, but they leave out the heat, repairs, mud, bills, laundry, spoiled food, and everything happening just outside the frame.",
  hero:"img/blog/2026-08-02-001.jpeg",
  alt:"Horizon parked at a beautiful mountain campsite",
  readingTime:"Medium",
  searchText:"photography life outside horizon heatwave durango vehicle living mud recovery repairs laundry executive dysfunction spoiled food bills camping reality outside the frame"
 },
 {url:"blog/2026-07-28-the-notebook-is-open-again.html",
 title:"The notebook is open again",
 date:"2026-07-28",
 year:2026,
 tags:["Notebook Update","Summer","Writing","Stories","Behind the Site"],
 excerpt:"The Notebook is finally easier to update, and regular summer stories, field notes, and older memories are on the way.",
 hero:"img/blog/2026-07-28-001.jpeg",
 alt:"An open notebook and laptop at a summer mountain campsite",
 readingTime:"Short",
 searchText:"notebook update summer writing weekly stories blog website field notes old memories regular posts"
 },
 {url:"blog/2026-07-25-about-the-fox.html",
 title:"About the fox",
 date:"2026-07-25",
 year:2026,
 tags:["Field Notes","Wildlife","Fox & Timber"],
 excerpt:"The small roadside encounter that quietly became part of a much larger creative story.",
 hero:"img/blog/2026-07-25-001.jpeg",
 alt:"A fox standing near a quiet campsite",
 readingTime:"Short",
 searchText:"fox scout wildlife roadside encounter company creative story photography"
},
{url:"blog/2026-07-18-living-between-destinations.html",
 title:"Living between destinations",
 date:"2026-07-18",
 year:2026,
 tags:["Life Outside","Horizon","Travel"],
 excerpt:"What home looks like when it has four wheels, a worn map, and a changing view.",
 hero:"img/blog/2026-07-18-001.jpeg",
 alt:"Horizon parked beside a remote forest road",
 readingTime:"Long",
 searchText:"home vehicle horizon travel road mobile living destinations camp"
},
{url:"blog/2026-07-12-why-i-keep-building-ideas.html",
 title:"Why I keep building ideas",
 date:"2026-07-12",
 year:2026,
 tags:["Making Things","Design","Creativity"],
 excerpt:"A notebook entry about design, unfinished projects, curiosity, and making things tangible.",
 hero:"img/blog/2026-07-12-001.jpeg",
 alt:"Sketches, notes, and design materials on a work surface",
 readingTime:"Long",
 searchText:"design unfinished projects curiosity ideas making creativity building tangible"
},
{
  url:"blog/2025-11-02-perfectionism-and-audhd.html",
  title:"The Beautiful Exhaustion: Living with Perfectionism and AuDHD",
  date:"2025-11-02",
  year:2025,
  tags: ["AuDHD","Perfectionism","Neurodiversity","Autism","ADHD"],
  excerpt:"A personal reflection on the beautiful exhaustion of perfectionism with autism and ADHD, and learning when something needs to be perfect versus simply done.",
  hero:"img/blog/2025-11-02-001.jpeg",
  alt:"A quiet, contemplative scene representing perfectionism and AuDHD",
  readingTime:"Medium",
  searchText:"audhd perfectionism neurodiversity autism adhd hyperfocus executive dysfunction anxiety burnout exhaustion impossible standards good enough"
},
 {
  url:"blog/2025-10-08-my-story.html",
  title:"Where do I begin? My story:",
  date:"2025-10-08",
  year:2025,
  tags: ["Personal Story","AuDHD","Neurodiversity","Autism","Life Outside"],
  excerpt:"An introductory story about my life, my late understanding of autism, ADHD, and Tourette’s, and the experiences that shaped the way I see and move through the world.",
  hero:"img/blog/2025-10-08-001.jpeg",
  alt:"Thirteen standing outdoors with mountains in the distance",
  readingTime:"Medium",
  searchText:"personal story audhd autism adhd tourettes neurodiversity masking childhood diagnosis sensory processing chronic pain truck life horizon"
}
];
