(()=>{"use strict";
      const notebookBase =
  window.NOTEBOOK_BASE || "/";

function notebookUrl(path) {
  return (
    notebookBase +
    String(path || "").replace(/^\/+/, "")
  );
}
      const L=Array.isArray(window.NOTEBOOK_LIBRARY)?window.NOTEBOOK_LIBRARY:[],g=document.querySelector("#notebook .post-grid"),m=document.querySelector("[data-notebook-modal]"),c=document.querySelector("[data-notebook-modal-content]"),x=document.querySelector("[data-notebook-modal-close]");if(!g||!L.length)return;const latest=[...L].filter(e=>e.url).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,3);g.replaceChildren();latest.forEach(e=>{const b=document.createElement("button");b.type="button";b.className="post-card notebook-home-card";b.dataset.url = notebookUrl(e.url);b.innerHTML=`<img src="${notebookUrl(e.hero)}" alt="${e.alt||e.title}" loading="lazy"><div class="post-card__body"><div class="post-meta"><span>${e.tags?.[0]||"Notebook"}</span><span>${e.readingTime||"Entry"}</span><span>${e.date}</span></div><h3>${e.title}</h3><p>${e.excerpt||""}</p></div>`;g.append(b)});async function open(u){if(!m||!c){location.href=u;return}c.innerHTML='<p class="lede">Loading entry…</p>';document.body.classList.add("notebook-modal-open");m.showModal();try{const r=await fetch(u);if(!r.ok)throw Error();const d=new DOMParser().parseFromString(await r.text(),"text/html"),a=d.querySelector("[data-notebook-entry]");if(!a)throw Error();const cl=a.cloneNode(true);cl.querySelector(".notebook-entry-actions")?.remove();cl.querySelector(".notebook-entry-nav")?.remove();cl.querySelectorAll("[src]").forEach(el=>{const v=el.getAttribute("src");if(v&&!v.startsWith("http")&&!v.startsWith("/"))el.src=new URL(v,new URL(u,location.href)).href});c.replaceChildren(cl);const l=document.createElement("a");l.className="button";l.href="blog.html";l.innerHTML='Read more posts <i class="fa-solid fa-book-open"></i>';c.append(l);x?.focus()}catch{c.innerHTML='<div class="callout"><strong>This entry could not be loaded.</strong></div><p><a class="button" href="blog.html">Read more posts</a></p>'}}function close(){if(m?.open)m.close();document.body.classList.remove("notebook-modal-open")}g.addEventListener("click",e=>{const b=e.target.closest("[data-url]");if(b)open(b.dataset.url)});x?.addEventListener("click",close);m?.addEventListener("cancel",e=>{e.preventDefault();close()})})();
