window.NOTEBOOK_BASE = "/";
window.NOTEBOOK_LIBRARY=[
{url:"blog/2026-07-25-about-the-fox.html",
 title:"About the fox",
 date:"2026-07-25",
 year:2026,
 tags:["Field Notes","Wildlife","Fox & Timber"],
 excerpt:"The small roadside encounter that quietly became part of a much larger creative story.",
 hero:"img/blog/2026-07-25-001.jpeg",
 alt:"A fox standing near a quiet campsite",
 readingTime:"Short",
 searchText:"fox scout wildlife roadside encounter company creative story"
},
{url:"blog/2026-07-18-living-between-destinations.html",
 title:"Living between destinations",
 date:"2026-07-18",
 year:2026,
 tags:["Life Outside","Horizon","Travel"],
 excerpt:"What home looks like when it has four wheels, a worn map, and a changing view.",
 hero:"img/blog/2026-07-18-001.jpeg",
 alt:"Horizon parked beside a remote forest road",
 readingTime:"Long",
 searchText:"home vehicle horizon travel road mobile living destinations camp"
},
{url:"blog/2026-07-12-why-i-keep-building-ideas.html",
 title:"Why I keep building ideas",
 date:"2026-07-12",
 year:2026,
 tags:["Making Things","Design","Creativity"],
 excerpt:"A notebook entry about design, unfinished projects, curiosity, and making things tangible.",
 hero:"img/blog/2026-07-12-001.jpeg",
 alt:"Sketches, notes, and design materials on a work surface",
 readingTime:"Long",
 searchText:"design unfinished projects curiosity ideas making creativity building tangible"
},
{
  url:"blog/2025-11-02-perfectionism-and-audhd.html",
  title:"The Beautiful Exhaustion: Living with Perfectionism and AuDHD",
  date:"2025-11-02",
  year:2025,
  tags: ["AuDHD","Perfectionism","Neurodiversity","Autism","ADHD"],
  excerpt:"A personal reflection on the beautiful exhaustion of perfectionism with autism and ADHD, and learning when something needs to be perfect versus simply done.",
  hero:"img/blog/2025-11-02-001.jpeg",
  alt:"A quiet, contemplative scene representing perfectionism and AuDHD",
  readingTime:"Medium",
  searchText:"audhd perfectionism neurodiversity autism adhd hyperfocus executive dysfunction anxiety burnout exhaustion impossible standards good enough"
},
 {
  url:"blog/2025-10-08-my-story.html",
  title:"Where do I begin? My story:",
  date:"2025-10-08",
  year:2025,
  tags: ["Personal Story","AuDHD","Neurodiversity","Autism","Life Outside"],
  excerpt:"An introductory story about my life, my late understanding of autism, ADHD, and Tourette’s, and the experiences that shaped the way I see and move through the world.",
  hero:"img/blog/2025-10-08-001.jpeg",
  alt:"Thirteen standing outdoors with mountains in the distance",
  readingTime:"Medium",
  searchText:"personal story audhd autism adhd tourettes neurodiversity masking childhood diagnosis sensory processing chronic pain truck life horizon"
}
];
